# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 631643f8d619459518bec2e7555a3b2597d71182d705f9ef326f32b4606277c6f40c74be3a2534d5649df30fbe753f2dd3f55518b59ad37371b6af1d3de125a3

test:
  secret_key_base: 19daee3abd36ad011cb2e6df151985362fa09f86cd07cf6a7c305e3e28f60053fa0a4d5b13185d26b71fda92c8351f756fc6e254ff2d191e00fb24d07054fe2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
